spring:
  application:
    name: sgave-mall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        # 后台商品 Swagger 文档
        - id: goods-docs
          uri: lb://sgave-mall-goods
          predicates:
            - Path=/goods/v3/api-docs
          filters:
            - StripPrefix=1
        # 后台商品 业务接口
        - id: goods
          uri: lb://sgave-mall-goods
          predicates:
            - Path=/goods/**,/excel/**
        # 后台库存 Swagger 文档
        - id: inventory-docs
          uri: lb://sgave-mall-inventory
          predicates:
            - Path=/inventory/v3/api-docs
          filters:
            - StripPrefix=1
        # 后台库存 业务接口
        - id: inventory
          uri: lb://sgave-mall-inventory
          predicates:
            - Path=/inventory/**
        # 后台订单 Swagger 文档
        - id: order-docs
          uri: lb://sgave-mall-order
          predicates:
            - Path=/admin-order/v3/api-docs
          filters:
            - StripPrefix=1
        # 后台订单 业务接口
        - id: order
          uri: lb://sgave-mall-order
          predicates:
            - Path=/admin-order/**
        # 后台用户 Swagger 文档
        - id: user-docs
          uri: lb://sgave-mall-user
          predicates:
            - Path=/user/v3/api-docs
          filters:
            - StripPrefix=1
        # 后台用户 user 业务接口
        - id: user
          uri: lb://sgave-mall-user
          predicates:
            - Path=/user/**,/admin/**
        ##################################################
        # web / 客户端服务 (sgave-mall-shopping)
        ##################################################
        # Swagger 文档
        - id: shopping-docs
          uri: lb://sgave-mall-shopping
          predicates:
            - Path=/customer/v3/api-docs
          filters:
            - StripPrefix=1
        # 业务接口
        - id: shopping
          uri: lb://sgave-mall-shopping
          predicates:
            - Path=/customer/**,/address/**,/cart/**,/web/**,/collect/**,/order/**,/footprint/**


jwt:
  white-list:
    - /admin/admin
    - /admin/logout
    - /customer/login
    - /customer/logout
    - /customer/register
    - /*/v3/api-docs
    - /web/**
  web-path-filters:
    - /customer/**
    - /cart/**
    - /address/**
    - /web/**
    - /collect/**
    - /order/**
    - /footprint/**
  admin-path-filters:
    - /goods/**
    - /inventory/**
    - /admin-order/**
    - /user/**
    - /excel/**



knife4j:
  gateway:
    enabled: true
    routes:
      - name: 商品服务
        url: /goods/v3/api-docs
        service-name: sgave-mall-goods

      - name: 库存服务
        url: /inventory/v3/api-docs
        service-name: sgave-mall-inventory

      - name: 订单服务
        url: /admin-order/v3/api-docs
        service-name: sgave-mall-order

      - name: 用户服务
        url: /user/v3/api-docs
        service-name: sgave-mall-user

      - name: web服务
        url: /customer/v3/api-docs
        service-name: sgave-mall-shopping
server:
  port: 9000
