spring:
  application:
    name: sgave-mall-order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.6:3306/mall?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: admin

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true


server:
  port: 9002